name: Veracode GitHub Action to ADO Test Workflow
on:
  workflow_dispatch:
    inputs:
      wait-time:
        description: 'Delay (in seconds) between entering Issues into GitHub (due to rate limiting)'
        type: 'string'
        required: false
        default: '2'
      source_base_path_1:
        description: 'Rewrite 1'
        type: 'string'
        required: false
      source_base_path_2:
        description: 'Rewrite 2'
        type: 'string'
        required: false
      source_base_path_3:
        description: 'Rewrite 3'
        type: 'string'
        required: false
      #repo_owner:
      #  description: 'repo owner'
      #  required: false
#      fail_build:
#        description: fail pipeline upon findings (true | false)
#        type: 'boolean'
#        default: 'false'
#        required: false
      autoCloseFindings:
        description: 'Automatically close issues/work items that are no longer present in scan results (true | false)'
        required: false
        default: 'false'
#      debug:
#        description: enable debug logging
#        type: 'boolean'
#        default: 'false'
#        required: false
      reponame:
        type: string
        required: false
        description: repo name to build
        default: 'veracode/verademo'
    #  adopat: # opting for the enviornment variable one that is set instead
    #    type: string
    #    required: false
    #    description: ADO PAT
      adoorg:
        type: string
        required: false
        description: ADO Org name
      adotype:
        description: ADO work item type name
        type: 'choice'
        options:
          - 'Bug'
          - 'Issue'
          - 'Task'
          - 'Epic'
          - 'Feature'
          - 'Test Case'
          - 'User Story'
        required: false
        default: 'Issue'
      adoproj:
        type: string
        description: ADO project name
        required: false
  push:
jobs:
  # This step will build the maven application
 
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: check inputs
        run: |
          echo ${{ github.repository.name }}
          echo ${{ github.event.inputs.wait-time }}
          echo ${{ github.event.inputs.source_base_path_1 }}
          echo ${{ github.event.inputs.source_base_path_2 }}
          echo ${{ github.event.inputs.source_base_path_3  }}
          echo ${{ github.event.inputs.autoCloseFindings }}
        
            
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.event.inputs.reponame }}
        
      - uses: actions/setup-java@v5
        with: 
          java-version: 22
          distribution: 'adopt'
          
      - name: Cache Maven packages
        uses: actions/cache@v4.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        continue-on-error: true

      - name: list out post java set up
        run: |
          ls -la
          
   
            
      - uses: actions/upload-artifact@v5
        with:
          name: verademo.war
          path: target/verademo.war
        

  # This step will run the Veracode pipeline scan 
  pipeline-scan:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - name: get archive
        uses: actions/download-artifact@v5
        with:
          name: verademo.war
          path: /tmp

      - run: ls -la /tmp

      
      - name: pipeline-scan
        run: | 
          java -jar /opt/veracode/pipeline-scan.jar \
            -vid "${{ secrets.VID }}" \
            -vkey "${{ secrets.VKEY }}" \
            --fail_on_severity="Very High, High" \
            --file /tmp/verademo.war \
            -jf results.json \
            -fjf filtered_results.json 
            
      - name: list directory
        run: ls
        #continue-on-error: true
      
      - name: save standard results
        uses: actions/upload-artifact@v5
        with:
          name: PipelineScanResults
          path: results.json
      
      - name: save filtered results
        uses: actions/upload-artifact@v5
        with:
          name: filtered-results
          path: filtered_results.json



#####################################################################################################
# Import flaws 
# The actual testing of the action
#
#####################################################################################################
        
  import_flaws_job:
    runs-on: ubuntu-latest
    needs: pipeline-scan
    name: import flaws

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: get flaw file
        uses: actions/download-artifact@v5
        with:
          name: filtered-results
      - name: confirm Flaw File Download
        run: | 
          ls -la
          file */*
          
      - name: Flaw importer action step
        id: import
        uses: ./
        with:
          scan-results-json: 'filtered_results.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source-base-path_1: "com/veracode:src/main/java/com/veracode" 
          source-base-path_2: "WEB-INF:src/main/webapp/WEB-INF"
          commit-hash: ${{ GITHUB.SHA }}
          dts_type: 'ADO'
            #description: 'Type of defect tracking system to use (GITHUB or ADO)'
            #required: false
            #default: 'GITHUB'
          #scan-results-json:
            #description: 'Scan results file'
            #required: true
            #default: 'filtered_results.json'
          #github-token:
            #description: 'GitHub token to access the repo'
            #default: ${{ github.token }}
            #required: true
          wait-time: '2'
            #description: 'Delay (in seconds) between entering Issues into GitHub (due to rate limiting)'
            #required: false
            #default: '2'
          #source_base_path_1:
            #description: 'Rewrite 1'
            #required: false
          #source_base_path_2:
            #description: 'Rewrite 2'
            #required: false
          #source_base_path_3:
            #description: 'Rewrite 3'
            #required: false
          #repo_owner:
            #description: 'repo owner'
            #required: false
          fail_build: true
            #description: fail pipeline upon findings (true | false)
            #required: false
          autoCloseFindings: true
            #description: 'Automatically close issues/work items that are no longer present in scan results (true | false)'
            #required: false
            #default: 'false'
          debug: true
            #description: enable debug logging
            #required: false
          #commitHash:
            #description: commit hash
            #required: false
          repo_name: ${{ github.event.inputs.reponame || vars.REPO_NAME }}
            #description: repo name
            #required: false
          ADO_PAT: ${{ github.event.inputs.adopat || secrets.ADO_PAT }}
            #description: 'Azure DevOps Personal Access Token'
            #required: false
          ADO_ORG: ${{ github.event.inputs.adoorg || secrets.ADO_ORG }}
            #description: 'Azure DevOps Organization'
            #required: false
          ADO_PROJECT: ${{ github.event.inputs.adoproj || secrets.ADO_PROJECT }}
            #description: 'Azure DevOps Project'
            #required: false
          ADO_WORK_ITEM_TYPE: ${{ github.event.inputs.adotype || secrets.ADO_WORK_ITEM_TYPE }}
            #description: 'Azure DevOps Work Item Type (Bug, Issue, Task, Epic, Feature, Test Case, User Story)'
            #required: false
            #default: 'Issue'
